import { Skill } from '../types/game';

export const BATTING_SKILLS: Record<string, Omit<Skill, 'unlockYear'>> = {
  cover_drive: {
    id: 'cover_drive',
    name: 'Cover Drive',
    type: 'batting',
    power: 7,
    risk: 3,
    staminaCost: 10,
    animation: 'cover_drive_anim',
    description: 'Classic cover drive through the off side',
  },
  helicopter_shot: {
    id: 'helicopter_shot',
    name: 'Helicopter Shot',
    type: 'batting',
    power: 9,
    risk: 7,
    staminaCost: 25,
    animation: 'helicopter_anim',
    description: 'Trademark finish over fine leg',
  },
  sweep: {
    id: 'sweep',
    name: 'Sweep Shot',
    type: 'batting',
    power: 7,
    risk: 5,
    staminaCost: 15,
    animation: 'sweep_anim',
    description: 'Aggressive sweep against spin',
  },
  defence: {
    id: 'defence',
    name: 'Solid Defence',
    type: 'batting',
    power: 5,
    risk: 1,
    staminaCost: 5,
    animation: 'defence_anim',
    description: 'Textbook defensive block',
  },
  pull_shot: {
    id: 'pull_shot',
    name: 'Pull Shot',
    type: 'batting',
    power: 8,
    risk: 6,
    staminaCost: 20,
    animation: 'pull_anim',
    description: 'Aggressive pull over square leg',
  },
  reverse_sweep: {
    id: 'reverse_sweep',
    name: 'Reverse Sweep',
    type: 'batting',
    power: 7,
    risk: 8,
    staminaCost: 22,
    animation: 'reverse_sweep_anim',
    description: 'Unorthodox reverse sweep',
  },
};

export const BOWLING_SKILLS: Record<string, Omit<Skill, 'unlockYear'>> = {
  yorker: {
    id: 'yorker',
    name: 'Yorker',
    type: 'bowling',
    power: 8,
    risk: 4,
    staminaCost: 20,
    animation: 'yorker_anim',
    description: 'Pinpoint yorker at the stumps',
  },
  outswing: {
    id: 'outswing',
    name: 'Outswing',
    type: 'bowling',
    power: 7,
    risk: 3,
    staminaCost: 15,
    animation: 'outswing_anim',
    description: 'Late outswing movement',
  },
  googly: {
    id: 'googly',
    name: 'Googly',
    type: 'bowling',
    power: 8,
    risk: 5,
    staminaCost: 18,
    animation: 'googly_anim',
    description: 'Deceptive googly delivery',
  },
  slower_ball: {
    id: 'slower_ball',
    name: 'Slower Ball',
    type: 'bowling',
    power: 7,
    risk: 6,
    staminaCost: 16,
    animation: 'slower_anim',
    description: 'Well disguised slower delivery',
  },
  bouncer: {
    id: 'bouncer',
    name: 'Bouncer',
    type: 'bowling',
    power: 8,
    risk: 5,
    staminaCost: 20,
    animation: 'bouncer_anim',
    description: 'Aggressive short pitched delivery',
  },
  doosra: {
    id: 'doosra',
    name: 'Doosra',
    type: 'bowling',
    power: 9,
    risk: 6,
    staminaCost: 22,
    animation: 'doosra_anim',
    description: 'The other one — turns the wrong way',
  },
};

export const FIELDING_SKILLS: Record<string, Omit<Skill, 'unlockYear'>> = {
  stumping: {
    id: 'stumping',
    name: 'Lightning Stumping',
    type: 'fielding',
    power: 8,
    risk: 2,
    staminaCost: 10,
    animation: 'stumping_anim',
    description: 'Fast hands stumping opportunity',
  },
};

export const FIELD_POSITIONS = [
  'slip',
  'gully',
  'point',
  'cover',
  'mid-off',
  'mid-on',
  'square leg',
  'fine leg',
  'third man',
  'deep midwicket',
  'long-on',
  'long-off',
] as const;
